export const LANGUAGES = [
  { code: "en", flag: "🇬🇧", label: "English" },
  { code: "es", flag: "🇪🇸", label: "Español" },
  { code: "fr", flag: "🇫🇷", label: "Français" },
  { code: "de", flag: "🇩🇪", label: "Deutsch" },
  { code: "pt", flag: "🇵🇹", label: "Português" },
  { code: "zh-CN", flag: "🇨🇳", label: "简体中文" },
  { code: "ja", flag: "🇯🇵", label: "日本語" },
  { code: "ko", flag: "🇰🇷", label: "한국어" },
  { code: "ar", flag: "🇸🇦", label: "العربية" },
  { code: "hi", flag: "🇮🇳", label: "हिन्दी" },
  { code: "it", flag: "🇮🇹", label: "Italiano" },
  { code: "nl", flag: "🇳🇱", label: "Nederlands" },
  { code: "tr", flag: "🇹🇷", label: "Türkçe" },
  { code: "pl", flag: "🇵🇱", label: "Polski" },
  { code: "ru", flag: "🇷🇺", label: "Русский" },
  { code: "id", flag: "🇮🇩", label: "Bahasa Indonesia" },
  { code: "vi", flag: "🇻🇳", label: "Tiếng Việt" },
  { code: "th", flag: "🇹🇭", label: "ไทย" },
  { code: "uk", flag: "🇺🇦", label: "Українська" },
  { code: "cs", flag: "🇨🇿", label: "Čeština" },
  { code: "sv", flag: "🇸🇪", label: "Svenska" },
  { code: "ro", flag: "🇷🇴", label: "Română" },
  { code: "el", flag: "🇬🇷", label: "Ελληνικά" },
  { code: "da", flag: "🇩🇰", label: "Dansk" },
  { code: "fi", flag: "🇫🇮", label: "Suomi" },
  { code: "no", flag: "🇳🇴", label: "Norsk" },
  { code: "he", flag: "🇮🇱", label: "עברית" },
  { code: "hu", flag: "🇭🇺", label: "Magyar" },
  { code: "ms", flag: "🇲🇾", label: "Bahasa Melayu" },
  { code: "fa", flag: "🇮🇷", label: "فارسی" },
  { code: "bn", flag: "🇧🇩", label: "বাংলা" },
  { code: "ta", flag: "🇮🇳", label: "தமிழ்" },
];

export const LANGUAGE_CODES = LANGUAGES.map(({ code }) => code);
